apiVersion: v1
kind: Namespace
metadata:
  name: barber-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: barber-pod
  namespace: barber-system
spec:
  selector:
    matchLabels:
      app: barber # Selector for POD name search.
  template:
    metadata:
      labels:
        app: barber
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: barber-api
        image: barber-api-image
        ports:
        - name: barber-api
          containerPort: 7000
        - name: barber-api-debug
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: barber-service
  namespace: barber-system
spec:
  type: ClusterIP
  selector:
    app: sales
  ports:
  - name: barber-api
    port: 7000
    targetPort: barber-api
  - name: barber-api-debug
    port: 8000
    targetPort: barber-api-debug
